name: FactionsPro
author: (old code) - Tethered_; (new code) - EpicDF, Derpific, Zeao
description: Official Faction Manager for ZapNetwork
version: 1.9.0
main: FactionsPro\FactionMain
api:
- 3.0.0
- 3.0.1
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
